lint:
	golint -set_exit_status ./...
	golangci-lint run -E goimports,unconvert,misspell,maligned,gocyclo,gocritic,gochecknoinits

test:
	go test -race -v ./...

xvfb-test:
	xvfb-run go test -race -v ./...
